// Copyright 2019-2026 @polkadot/extension-polkagate authors & contributors
// SPDX-License-Identifier: Apache-2.0

export const SUBSCAN_CHAINS_ENDPOINT = {
  acala: 'acala.subscan.io',
  altair: 'altair.subscan.io',
  'assethub-kusama': 'assethub-kusama.subscan.io',
  'assethub-paseo': 'assethub-paseo.subscan.io',
  'assethub-polkadot': 'assethub-polkadot.subscan.io',
  'assethub-westend': 'assethub-westend.subscan.io',
  astar: 'astar.subscan.io',
  autonomys: 'autonomys.subscan.io',
  'autonomys-chronos': 'autonomys-chronos.subscan.io',
  avail: 'avail.subscan.io',
  'avail-turing': 'avail-turing.subscan.io',
  basilisk: 'basilisk.subscan.io',
  'bifrost-kusama': 'bifrost-kusama.subscan.io',
  'bifrost-polkadot': 'bifrost.subscan.io',
  'bridgehub-kusama': 'bridgehub-kusama.subscan.io',
  'bridgehub-paseo': 'bridgehub-paseo.subscan.io',
  'bridgehub-polkadot': 'bridgehub-polkadot.subscan.io',
  'bridgehub-westend': 'bridgehub-westend.subscan.io',
  centrifuge: 'centrifuge-standalone-history.subscan.io',
  'centrifuge-parachain': 'centrifuge.subscan.io',
  collectives: 'collectives-polkadot.subscan.io',
  'coretime-kusama': 'coretime-kusama.subscan.io',
  'coretime-paseo': 'coretime-paseo.subscan.io',
  'coretime-polkadot': 'coretime-polkadot.subscan.io',
  'coretime-westend': 'coretime-westend.subscan.io',
  creditcoin: 'cc-enterprise.subscan.io',
  'creditcoin-cc3': 'creditcoin.subscan.io',
  'creditcoin-cc3-test': 'creditcoin3-testnet.subscan.io',
  'creditcoin-dev': 'creditcoin3-dev.subscan.io',
  'crust-main': 'crust.subscan.io',
  'crust-parachain': 'crust-parachain.subscan.io',
  'dancelight-test': 'dancelight.subscan.io',
  darwinia: 'darwinia.subscan.io',
  energywebx: 'energywebx.subscan.io',
  'energywebx-testnet': 'energywebx-testnet.subscan.io',
  'enjin-canary-matrix': 'canary-matrix.subscan.io',
  'enjin-canary-relay': 'canary.subscan.io',
  'enjin-matrix': 'matrix.subscan.io',
  'enjin-relay': 'enjin.subscan.io',
  heima: 'heima.subscan.io',
  humanode: 'humanode.subscan.io',
  hydradx: 'hydration.subscan.io',
  karura: 'karura.subscan.io',
  khala: 'khala.subscan.io',
  krest: 'krest.subscan.io',
  kusama: 'kusama.subscan.io',
  manta: 'manta.subscan.io',
  midnight: 'midnight.subscan.io',
  'midnight-preprod': 'midnight-preprod.subscan.io',
  'midnight-preview': 'midnight-preview.subscan.io',
  moonbase: 'moonbase.subscan.io',
  moonbeam: 'moonbeam.subscan.io',
  moonriver: 'moonriver.subscan.io',
  mythos: 'mythos.subscan.io',
  neuroweb: 'neuroweb.subscan.io',
  'neuroweb-testnet': 'neuroweb-testnet.subscan.io',
  paseo: 'paseo.subscan.io',
  'peaq-main': 'peaq.subscan.io',
  'peaq-testnet': 'agung-testnet.subscan.io',
  pendulum: 'pendulum.subscan.io',
  'people-kusama': 'people-kusama.subscan.io',
  'people-paseo': 'people-paseo.subscan.io',
  'people-polkadot': 'people-polkadot.subscan.io',
  'people-westend': 'people-westend.subscan.io',
  phala: 'phala.subscan.io',
  polkadot: 'polkadot.subscan.io',
  polymesh: 'polymesh.subscan.io',
  'polymesh-test': 'polymesh-testnet.subscan.io',
  reef: 'reef.subscan.io',
  'robonomics-polkadot': 'robonomics.subscan.io',
  shibuya: 'shibuya.subscan.io',
  shiden: 'shiden.subscan.io',
  'space-time': 'sxt.subscan.io',
  stafi: 'stafi.subscan.io',
  tanssi: 'tanssi.subscan.io',
  vara: 'vara.subscan.io',
  vflow: 'vflow.subscan.io',
  westend: 'westend.subscan.io',
  zkverify: 'zkverify.subscan.io',
  'zkverify-testnet': 'zkverify-testnet.subscan.io'
} as const;

export type SubscanChain = keyof typeof SUBSCAN_CHAINS_ENDPOINT;

export const SUBSCAN_CHAINS = Object.keys(SUBSCAN_CHAINS_ENDPOINT);
